import type { Invoice } from './types';

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

function formatAmount(amount: number): string {
  return `£${Math.abs(amount).toFixed(2)}`;
}

export function generateInvoiceHTML(invoice: Invoice, businessName?: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #0F172A; padding: 40px; }
    .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .brand { font-size: 28px; font-weight: 700; color: #1E3A8A; }
    .invoice-label { font-size: 32px; font-weight: 300; color: #64748B; text-align: right; }
    .invoice-number { font-size: 14px; color: #64748B; text-align: right; margin-top: 4px; }
    .details { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .details-section h3 { font-size: 11px; text-transform: uppercase; color: #64748B; letter-spacing: 1px; margin-bottom: 8px; }
    .details-section p { font-size: 14px; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
    th { background: #F1F5F9; padding: 12px 16px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748B; }
    td { padding: 16px; border-bottom: 1px solid #E2E8F0; font-size: 14px; }
    .amount { text-align: right; font-weight: 600; }
    .total-row { border-top: 2px solid #0F172A; }
    .total-row td { font-size: 18px; font-weight: 700; padding-top: 16px; }
    .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #E2E8F0; font-size: 12px; color: #94A3B8; text-align: center; }
    .status { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; }
    .status-paid { background: #DCFCE7; color: #16A34A; }
    .status-sent { background: #DBEAFE; color: #1E3A8A; }
    .status-overdue { background: #FEE2E2; color: #DC2626; }
    .status-draft { background: #F1F5F9; color: #64748B; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">${escapeHtml(businessName || 'QuidSafe')}</div>
    <div>
      <div class="invoice-label">INVOICE</div>
      <div class="invoice-number">#${invoice.id.slice(0, 8).toUpperCase()}</div>
    </div>
  </div>
  <div class="details">
    <div class="details-section">
      <h3>Bill To</h3>
      <p><strong>${escapeHtml(invoice.clientName)}</strong></p>
    </div>
    <div class="details-section" style="text-align: right;">
      <h3>Invoice Details</h3>
      <p>Due: ${formatDate(invoice.dueDate)}</p>
      <p>Status: <span class="status status-${escapeHtml(invoice.status)}">${escapeHtml(invoice.status.toUpperCase())}</span></p>
      ${invoice.paidAt ? `<p>Paid: ${formatDate(invoice.paidAt)}</p>` : ''}
    </div>
  </div>
  <table>
    <thead><tr><th>Description</th><th class="amount">Amount</th></tr></thead>
    <tbody>
      <tr><td>${escapeHtml(invoice.description)}</td><td class="amount">${formatAmount(invoice.amount)}</td></tr>
    </tbody>
    <tfoot>
      <tr class="total-row"><td><strong>Total</strong></td><td class="amount">${formatAmount(invoice.amount)}</td></tr>
    </tfoot>
  </table>
  <div class="footer">Generated by QuidSafe - UK Sole Trader Tax Assistant</div>
</body>
</html>`;
}
